### ISSUE TITLE
does not install the module itself when installed from pip

### ISSUE THREAD

**Issue by vvch** [histrio/python-descript-ion#8]
When installed using `pip`, only metadata are installed, no module code:
```
$ pip3 show -f descript
Name: descript
Version: 0.0.1
Summary: UNKNOWN
Home-page: https://github.com/histrio/python-descript-ion
Author: Rinat F Sabitov
Author-email: rinat.sabitov@gmail.ru
License: UNKNOWN
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: 
Files:
  descript-0.0.1.dist-info/INSTALLER
  descript-0.0.1.dist-info/METADATA
  descript-0.0.1.dist-info/RECORD
  descript-0.0.1.dist-info/WHEEL
  descript-0.0.1.dist-info/top_level.txt
```

**Comment by histrio** [comment]
Thanks, @vvch ! I'm surprised that somebody tried that lib :) 
I will fix it in no time.

**Comment by vvch** [comment]
> I'm surprised that somebody tried that lib :)

Seems like your lib is the only existing solution for this task :) Of course it is not a big deal to write my own lib, but if there is one already I prefer to use it.
